name: setup monorepo
description: configures pnpm, turbo, and build core libs

inputs:
  ref:
    description: 'git ref/tag to checkout and prepare'
    default: main
  run:
    description: 'shell script / commands to run with the turbo repo token already configured'
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      env:
        FOO: overridden
        BAR: bam
      run: |
        set -e
        
        echo '----------------------------------------------------------------------------'
        ${{ inputs.run }}
        echo '----------------------------------------------------------------------------'