name: 'Test Workflow'
on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [ 1, 2 ]
    steps:
      - run: echo 'hello world'
  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      echo '---------------------------------------'
      echo '${{ job-one.strategy.job-total }}'
      echo '---------------------------------------'