name: 'Test Workflow'
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - env:
        GITHUB_BUILD_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: echo "${GITHUB_BUILD_LINK}"
