name: 'Test Workflow'
on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [ 1, 2 ]
    steps:
      - run: |
          echo 'hello world'
          echo '${{ strategy.job-total }}'
  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '---------------------------------------'
          echo '${{ needs.job-one.strategy.job-total }}'
          echo '---------------------------------------'