name: 'Test Workflow'
on:
  push:

jobs:
  job-one:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [ 1, 2 ]
    outputs:
      SHARD_COUNT: ${{ steps.step1.outputs.SHARD_COUNT }}
    steps:
      - run: |
          echo 'hello world'
          echo SHARD_COUNT='${{ strategy.job-total }}' >> $GITHUB_OUTPUT
  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - run: |
          +x
          echo '${{ needs.job-one.outputs.SHARD_COUNT }}'